# Fabric version properties for version-26-2
minecraft_version_26_2 = 26.2
loader_version_26_2 = 0.19.3
loom_version_26_2 = 1.17.14
fabric_api_version_26_2 = 0.154.2+26.2

# Fabric version properties for version-1-21-11
minecraft_version_1_21_11 = 1.21.11
loader_version_1_21_11 = 0.16.8
loom_version_1_21_11 = 1.17.14
fabric_api_version_1_21_11 = 0.141.4+1.21.11

# Common
java_version = 21
